version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: phpmvc-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9003:9003"
    volumes:
      - ./:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
  nginx:
    image: nginx:alpine
    container_name: phpmvc-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: phpmvc-db
    image: mysql
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
