services:
  app:
    container_name: mvc_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
  web:
    container_name: mvc_web
    image: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8000:80
    links:
      - app
  database:
    container_name: mvc_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mvcdb
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  app-network:
    driver: bridge
