version: "3"

services:
  app:
    build:
      dockerfile: ./PHP/Dockerfile
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
