version: '3'

services:
  php:
    build:
      context: .
    ports:
      - "8008:80"

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
